### ISSUE TITLE
Results show more samples than samples in input

### ISSUE THREAD

**Issue by pablovgd** [bihealth/NeatMS#5]
Dear

I have been trying out NeatMS on LC-MS data processed with XCMS.
First remark: not all my peaks in XCMS were assigned to a feature, which caused the presence of NA's in the feature.id column of some peaks, so I deleted the peaks that didn't get a feature assigned, I'm not quite sure if this is good practice.
Everything else seems to be working as expected, but when I took a look at the results (using the code from the tutorial) I get this output:

```
# Feature collection: 7124
Number of consensus features labeled as 'High quality':
   of size 10 :   2100
   of size  9 :    953
   of size  0 :    749
   of size  8 :    668
   of size  7 :    532
   of size  6 :    431
   of size  4 :    362
   of size  1 :    345
   of size  5 :    336
   of size  3 :    281
   of size  2 :    262
   of size 11 :     27
   of size 13 :     16
   of size 12 :     14
   of size 14 :     10
   of size 15 :      9
   of size 20 :      8
   of size 19 :      7
   of size 16 :      6
   of size 17 :      6
   of size 18 :      1
   of size 23 :      1
        total :   7124
```
If I understand it correctly, this says that the amount of features present in x samples is y. So how can a feature be present in more samples than there are input samples (10)?

All files for reproducing are attached. And mzML files can be downloaded here: https://we.tl/t-mWPcWAXEGc
aligned peaks: [aligned_pos_no_NA.csv](https://github.com/bihealth/NeatMS/files/9009884/aligned_pos_no_NA.csv)
notebook: [NeatMS.zip](https://github.com/bihealth/NeatMS/files/9009897/NeatMS.zip)

Thanks in advance for the help!

Kind regards
Pablo

**Comment by yoglo** [comment]
Hi Pablo,

Regarding your first remark, XCMS only assigns a feature id to peaks that can be aligned across multiple samples (the minimum number of samples being a parameter I believe). Having NAs in the feature.id column is handled by NeatMS, the feature will only contain a peak in one sample. Did you have any problem loading the feature table when keeping the NAs in?

The second point you mentioned is a known behaviour specific to XCMS. When aligning peaks using XCMS, it sometimes happens that two very close peaks within the same samples are "grouped together" and assigned to the same feature. This behaviour is actually hidden from the user as only the intensity of one peak is reported when exporting the features (still in XCMS), the information is only available when looking at the peak ids associated with a feature. 
Since NeatMS only purpose is to assign quality labels to peaks without modifying the data, we decided to report all peaks when such case happens and leave this selection to the user. You can reduce the number of such "duplicate peaks" by changing the parameters of the alignment function in XCMS, but it is likely that you will always have a few left in your data.

That is not currently something we are planning to change as it would result in data loss if we were to implement any kind of peak selection for the reporting.

I hope this help.

Regards,
Yoann

**Comment by pablovgd** [comment]
Hi Yoann

Thanks for the elaborate response!

I didn't get any problems loading in my data with NA's ([aligned_pos.zip](https://github.com/bihealth/NeatMS/files/9010715/aligned_pos.zip)), but then NeatMS reported 82458 features and 148581 peaks instead of 7123 features and 70115 peaks that is reported in the dataset with the NA (so peaks without features removed). And normally (acc. XCMS) I am expecting 7137 features. 

Second point: 
Ok, so the correct way to read the output is more like: "2100 features are found in 10 peaks each", "953 features are found in 9 peaks each" ,... and 1 feature is found in 23 peaks. Correct?

**Comment by yoglo** [comment]
The numbers seem to be right by looking into your original .csv file (with NA). There are 148581 peaks, 73260 of them are attached to 7137 features and 75321 peaks have no feature (NA in feature_id column). 

In NeatMS, those independent peaks are also considered as features (this is just how the data structure is built). When loading the data, for every "orphan" peak, a new feature containing a single peak is created on the fly, which results in 82458 features (7137 with multiple peaks and 75321 with only one peak). These can be excluded during NeatMS export but your approach of cleaning up the data before loading it seems fine to me unless you are interested in peaks only present in a single sample. I could not make sense of the 7123 number by just looking at the file, I assume some features/peaks might be excluded during the sanity check. 

Regarding the second point, you original interpretation was correct: "2100 features contain 10 high quality peaks". This snippet was originally created for mzmine data where a sample can only have one peak attached to a specific feature. In which case, it could be read as "2100 features have high quality peaks in all 10 samples". Due to the multiple peak - feature assignment behaviour of XCMS, this is not valid anymore (although probably close). In order to replicate that with XCMS data, we would have to change the snippet to only count one peak per sample (but we would have to make a decision on which peak to select again). 

I hope this clarify things.
